#181 show npm and node version
because I was getting an error when running the elm tests

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode